dist: bionic

language: go

go:
    - 1.13.x

install:
    - go get -u github.com/gohugoio/hugo
    - pip install --user urllib3[secure]
    - pip install --user awscli
    - aws configure set preview.cloudfront true

script:
    - make deploy
